name: manual-trigger-hello
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Print other
        run: echo "ciao"
      - name: commands in yaml literal block
        run: |
          echo "First  output in literal block"
          echo "Second output in literal block"
          echo "Third  output in literal block"

